import type { InferInsertModel } from "drizzle-orm";
import type {
  leadSources,
  leadTypes,
  leads,
  properties,
} from "./db/schema";

// Development fixtures for the CRM (§47). Every person here is invented — no
// real customer data. Phone numbers use the 99000 test block so nobody's actual
// phone rings if a seeded database is pointed at a live dialler.

export const leadTypeSeed: InferInsertModel<typeof leadTypes>[] = [
  { key: "buyer", label: "Buyer", sortOrder: 10 },
  { key: "seller", label: "Seller", sortOrder: 20 },
  { key: "investor", label: "Investor", sortOrder: 30 },
  { key: "tenant", label: "Tenant", sortOrder: 40 },
  { key: "landlord", label: "Landlord", sortOrder: 50 },
  { key: "nri", label: "NRI", sortOrder: 60 },
  { key: "general", label: "General enquiry", sortOrder: 70 },
];

export const leadSourceSeed: InferInsertModel<typeof leadSources>[] = [
  { key: "website", label: "Website", sortOrder: 10 },
  { key: "property_page", label: "Property page", sortOrder: 20 },
  { key: "contact_form", label: "Contact form", sortOrder: 30 },
  { key: "whatsapp", label: "WhatsApp", sortOrder: 40 },
  { key: "phone", label: "Phone", sortOrder: 50 },
  { key: "referral", label: "Referral", sortOrder: 60 },
  { key: "instagram", label: "Instagram", sortOrder: 70 },
  { key: "facebook", label: "Facebook", sortOrder: 80 },
  { key: "google", label: "Google", sortOrder: 90 },
  { key: "walk_in", label: "Walk-in", sortOrder: 100 },
  { key: "employee", label: "Employee", sortOrder: 110 },
  { key: "other", label: "Other", sortOrder: 120 },
];

/**
 * Three extra listings covering the shapes the original four don't: bare
 * residential land, a standalone residential building, and a commercial unit.
 * All start as drafts — Rule 1 applies to seeded rows too.
 */
export const extraPropertySeed: InferInsertModel<typeof properties>[] = [
  {
    id: "palm-grove-land-aluva",
    reference: "LIV-0005",
    name: "Palm Grove Plot",
    locality: "Aluva",
    city: "Ernakulam",
    type: "Residential land",
    summary:
      "A quiet 12-cent residential plot near the Aluva metro, with clear title and 30 ft road access.",
    description:
      "Level ground, coconut and mango on the boundary, and a 30 ft tarred road to the frontage. Suits a single large home or two compact plots.",
    kind: "residential",
    listingType: "sale",
    status: "Ready to move",
    priceLabel: "₹96 L",
    priceValue: 9600000,
    askingPrice: 9600000,
    beds: 0,
    baths: 0,
    area: "12 cents",
    amenities: ["Clear title", "30 ft road access", "Corner plot", "Well on site"],
    details: [
      { label: "Plot", value: "12 cents" },
      { label: "Frontage", value: "80 ft" },
      { label: "Zoning", value: "Residential" },
    ],
    gallery: ["/images/hero-kochi-home.jpg"],
    hasBuilding: false,
    landArea: 12,
    landAreaUnit: "cent",
    surveyNumber: "412/3B",
    roadAccess: "30 ft tarred",
    facing: "North",
    district: "Ernakulam",
    state: "Kerala",
    pincode: "683101",
    country: "India",
    sortOrder: 5,
    workflowStatus: "draft",
    isPublic: false,
  },
  {
    id: "the-old-bungalow-fort-kochi",
    reference: "LIV-0006",
    name: "The Old Bungalow",
    locality: "Fort Kochi",
    city: "Kochi",
    type: "4 BHK heritage home",
    summary:
      "A restored colonial-era bungalow off Princess Street — teak floors, deep verandas and a walled garden.",
    description:
      "Four bedrooms across two floors, restored in 2021 with the original teak and Athangudi tiles kept intact. Walled garden, outhouse and parking for three cars.",
    kind: "residential",
    listingType: "both",
    status: "Ready to move",
    priceLabel: "₹5.40 Cr",
    priceValue: 54000000,
    askingPrice: 54000000,
    rentalIncome: 180000,
    rentalFrequency: "monthly",
    beds: 4,
    baths: 4,
    area: "4,200 sqft",
    amenities: [
      "Walled garden",
      "Restored teak interiors",
      "Outhouse",
      "Covered parking",
      "Rainwater harvesting",
    ],
    details: [
      { label: "Configuration", value: "4 BHK" },
      { label: "Built-up area", value: "4,200 sqft" },
      { label: "Plot", value: "18 cents" },
      { label: "Year restored", value: "2021" },
    ],
    gallery: ["/images/story-living-room.jpg", "/images/story-detail.jpg"],
    hasBuilding: true,
    builtUpArea: 4200,
    builtUpAreaUnit: "sqft",
    floors: 2,
    landArea: 18,
    landAreaUnit: "cent",
    parking: "3 covered",
    propertyAge: "Restored 2021",
    furnishedStatus: "Semi-furnished",
    facing: "West",
    district: "Ernakulam",
    state: "Kerala",
    pincode: "682001",
    country: "India",
    sortOrder: 6,
    workflowStatus: "draft",
    isPublic: false,
  },
  {
    id: "infopark-office-suite-kakkanad",
    reference: "LIV-0007",
    name: "InfoPark Office Suite",
    locality: "Kakkanad",
    city: "Ernakulam",
    type: "Grade A office floor",
    summary:
      "A fitted 6,500 sqft office floor on the InfoPark expressway, ready for a 90-seat team.",
    description:
      "Full floor with existing fit-out — cabins, meeting rooms, server room and pantry. Power backup, two lifts and 20 covered parking bays.",
    kind: "commercial",
    commercialKind: "office",
    listingType: "rental",
    status: "Ready to move",
    priceLabel: "₹4.5 L / month",
    priceValue: 0,
    rentalIncome: 450000,
    rentalFrequency: "monthly",
    rentalYield: 7.5,
    beds: 0,
    baths: 4,
    area: "6,500 sqft",
    amenities: [
      "Existing fit-out",
      "100% power backup",
      "Two lifts",
      "20 covered parking bays",
      "Server room",
    ],
    details: [
      { label: "Carpet area", value: "6,500 sqft" },
      { label: "Floor", value: "4th of 8" },
      { label: "Seats", value: "~90" },
    ],
    gallery: ["/images/about-city.jpg"],
    hasBuilding: true,
    builtUpArea: 6500,
    builtUpAreaUnit: "sqft",
    floorNumber: "4th of 8",
    occupancy: "Vacant",
    suitableFor: "IT / back office",
    leasePotential: "5-year lease, 5% annual escalation",
    parking: "20 covered",
    district: "Ernakulam",
    state: "Kerala",
    pincode: "682030",
    country: "India",
    sortOrder: 7,
    workflowStatus: "draft",
    isPublic: false,
  },
];

type LeadSeed = Omit<InferInsertModel<typeof leads>, "id" | "reference"> & {
  /** Listings this fictional lead enquired about. */
  interestedIn?: string[];
  /** Notes to append, oldest first. */
  notes?: string[];
};

export const leadSeed: LeadSeed[] = [
  {
    name: "Anjali Menon",
    mobile: "+91 99000 10001",
    email: "anjali.menon@example.com",
    city: "Ernakulam",
    typeKey: "buyer",
    propertyKind: "residential",
    requirementType: "buy",
    preferredLocation: "Kakkanad, Panampilly Nagar",
    budgetMin: 15000000,
    budgetMax: 22000000,
    bedrooms: 3,
    timeline: "1-3m",
    purpose: "own_use",
    status: "qualified",
    priority: "hot",
    sourceKey: "property_page",
    initialMessage:
      "We're moving back from Bangalore in March and want something ready to occupy near InfoPark.",
    interestedIn: ["the-arbour-kakkanad", "the-terraces-panampilly"],
    notes: ["Called — wants a weekend viewing for both Kakkanad options."],
  },
  {
    name: "Rajesh Pillai",
    mobile: "+91 99000 10002",
    email: "rajesh.pillai@example.com",
    city: "Kochi",
    typeKey: "seller",
    propertyKind: "residential",
    requirementType: "sell",
    preferredLocation: "Fort Kochi",
    status: "contacted",
    priority: "warm",
    sourceKey: "referral",
    initialMessage:
      "Looking to sell my father's bungalow in Fort Kochi. Referred by the Nair family.",
    notes: ["Valuation visit booked. Wants a discreet, off-market sale."],
  },
  {
    name: "Deepa Krishnan",
    mobile: "+91 99000 10003",
    email: "deepa.k@example.com",
    city: "Dubai",
    country: "United Arab Emirates",
    typeKey: "nri",
    propertyKind: "residential",
    requirementType: "buy",
    preferredLocation: "Marine Drive",
    budgetMin: 35000000,
    budgetMax: 45000000,
    timeline: "3-6m",
    purpose: "investment",
    status: "site_visit_scheduled",
    priority: "hot",
    sourceKey: "instagram",
    utmSource: "instagram",
    utmMedium: "social",
    utmCampaign: "waterfront-launch",
    initialMessage:
      "In Kochi for two weeks in February. Would like to see the waterfront villas then.",
    interestedIn: ["riverstone-villas-marine-drive"],
    notes: [
      "Family will view on her behalf if the dates slip.",
      "Wants NRI documentation support — repatriation questions.",
    ],
  },
  {
    name: "Suresh Varma",
    mobile: "+91 99000 10004",
    email: "suresh.varma@example.com",
    city: "Ernakulam",
    typeKey: "investor",
    propertyKind: "commercial",
    requirementType: "buy",
    preferredLocation: "Kakkanad",
    budgetMin: 40000000,
    budgetMax: 80000000,
    timeline: "6m+",
    purpose: "rental",
    status: "negotiation",
    priority: "warm",
    sourceKey: "walk_in",
    initialMessage: "Looking for a tenanted commercial floor with a steady yield.",
    notes: ["Comparing three options. Yield is the deciding factor, not price."],
  },
  {
    name: "Fathima Rasheed",
    mobile: "+91 99000 10005",
    email: "fathima.r@example.com",
    city: "Ernakulam",
    typeKey: "tenant",
    propertyKind: "residential",
    requirementType: "rent",
    preferredLocation: "Aluva, Edappally",
    budgetMin: 25000,
    budgetMax: 40000,
    bedrooms: 2,
    timeline: "immediate",
    purpose: "own_use",
    status: "new",
    priority: "cold",
    sourceKey: "google",
    utmSource: "google",
    utmMedium: "cpc",
    initialMessage: "Need a 2 BHK near the metro from next month.",
  },
];
